include:
  - compose/profiles/mock-build-simple-compose.yaml
  - compose/profiles/mock-create-simple-compose.yaml
  - compose/profiles/mock-publish-simple-compose.yaml
  - compose/profiles/mock-account-login-compose.yaml

services:
  genaiz-it:
    container_name: genaiz_it_reporter
    image: genaiz.com/sdk/genaiz-it:latest
    command: --version > version.txt
    volumes:
      - ${ROOT_MOUNT:-.}:/home/genaiz
    profiles:
      - report