name: alpine-default
aliases:
  - alpine
  - alpine_default
  - alpine.default
type: function
artifacts:
  - name: Dockerfile.tmpl
    dest: Dockerfile
    commands:
      - "mv Dockerfile.tmpl Dockerfile"
  - name: .dockerignore.tmpl
    dest: .dockerignore
    commands:
      - "mv .dockerignore.tmpl .dockerignore"
initParams:
  input: run/in
  output: run/{timestamp}/out
  var: run/{timestamp}/var
  log: run/{timestamp}/log
initCommands:
  - "ls /bin/bash"
postCommands:
  - 'mkdir -p {{or .mount_in .input "input"}}'
  - 'mkdir -p {{or .mount_out .output "output"}}'
  - 'mkdir -p {{or .mount_log .log "output/log"}}'
  - 'mkdir -p {{or .mount_var .var "output/var"}}'