services:
  registry:
    container_name: genaiz_registry
    image: registry:latest
    environment:
      - "REGISTRY_AUTH=token"
      - "REGISTRY_AUTH_TOKEN_REALM=http://broker:8081/v1/token"
      - "REGISTRY_AUTH_TOKEN_SERVICE=registry:5000"
      - "REGISTRY_AUTH_TOKEN_AUTOREDIRECT=false"
      - "REGISTRY_AUTH_TOKEN_ISSUER=iss.genaiz.com"
      - "REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=${AUTH_PATH}/bundle.crt"
      - "REGISTRY_AUTH_TOKEN_JWKS=${AUTH_PATH}/keys.jwks"
      - "REGISTRY_STORAGE_DELETE_ENABLED=false"
      - "REGISTRY_LOG_LEVEL=debug"
      - "OTEL_TRACES_EXPORTER=none"
    ports:
      - "5000:5000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://0.0.0.0:5000/"]
      start_period: 5s
      interval: 15s
      timeout: 5s
      retries: 3
    profiles:
      - services-registry