services:
  wiremock:
    container_name: genaiz_wiremock
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://0.0.0.0:8080/favicon.ico" ]
      start_period: 3s
      interval: 15s
      timeout: 3s
      retries: 3
    profiles:
      - services-wiremock