FROM alpine:3.22.2

{{- $bin_path := or .SF_BIN_PATH "/opt/genaiz/bash-example/bin"}}

RUN apk add --no-cache bash
RUN mkdir -p /mnt/in  \
    && mkdir -p /mnt/out \
    && mkdir -p /mnt/log \
    && mkdir -p /mnt/var
RUN chmod 555 /mnt/in
RUN chmod 777 /mnt/out /mnt/log /mnt/var
ADD app.sh {{$bin_path}}/
RUN chmod 755 {{$bin_path}}/app.sh

CMD ["{{$bin_path}}/app.sh"]
