name: bash-example
aliases:
  - bash_ex
  - bash_example
  - bash.example
type: function
artifacts:
  - name: app.sh.tmpl
    commands:
      - "mv app.sh.tmpl app.sh"
      - "chmod 0750 app.sh"
  - name: Dockerfile.tmpl
    commands:
      - "mv Dockerfile.tmpl Dockerfile"
initParams:
  input: run/in
  output: run/{timestamp}/out
  var: run/{timestamp}/var
  log: run/{timestamp}/log
initCommands:
  - "ls /bin/bash"
postCommands:
  - 'mkdir -p {{or .mount_in .input "input"}}'
  - 'mkdir -p {{or .mount_out .output "output"}}'
  - 'mkdir -p {{or .mount_log .log "output/log"}}'
  - 'mkdir -p {{or .mount_var .var "output/var"}}'