include:
  - ../services/mock-broker-compose.yaml

services:
  genaiz-mock-account-login:
    depends_on:
      wiremock:
        condition: service_healthy
    container_name: genaiz_mock_account_login
    image: genaiz.com/sdk/genaiz:latest
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    command: ac login wiremock:8080 --username _test@genaiz.com --logLevel=debug
    environment:
      - GENAIZ_PASSWORD=success
    volumes:
      - ${TESTS_MOUNT:-.}/mock-account-login:/home/genaiz/.cache/genaiz
    profiles:
      - mock-account-login