name: Debian Package
on:
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Go Setup
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.2'

      - name: Go Compile
        run: |
          cd genaiz && make build

      - name: Setup Version
        run: echo "GENAIZ_VERSION=$(./genaiz/genaiz --version |cut -d' ' -f3)" >> $GITHUB_ENV

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential binutils

      - name: Prepare directory structure
        run: |
          mkdir -p genaiz_${{env.GENAIZ_VERSION}}_amd64/usr/local/bin
          mkdir -p genaiz_${{env.GENAIZ_VERSION}}_amd64/DEBIAN

      - name: Copy application files
        run: |
          cp genaiz/genaiz genaiz_${{env.GENAIZ_VERSION}}_amd64/usr/local/bin/genaiz
          chmod +x genaiz_${{env.GENAIZ_VERSION}}_amd64/usr/local/bin/genaiz

      - name: Create control file
        run: |
          cat <<EOF > genaiz_${{env.GENAIZ_VERSION}}_amd64/DEBIAN/control
          Package: genaiz
          Version: ${{env.GENAIZ_VERSION}}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libc6
          Description: GenAIz SDK tool
          EOF

      - name: Build DEB package
        run: dpkg-deb --build --root-owner-group genaiz_${{env.GENAIZ_VERSION}}_amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: deb-package
          path: genaiz_${{env.GENAIZ_VERSION}}_amd64.deb

      - name: Fetch Public Email
        id: fetch_email_step
        uses: actions/github-script@v7
        with:
          script: |
            const user = await github.rest.users.getByUsername({
              username: context.actor
            });
            const email = user.data.email || `${context.actor}@users.noreply.github.com`;
            
            // Set the output variable named 'user_email'
            core.setOutput('user_email', email);

      - name: Tag
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ steps.fetch_email_step.user_email }}"
          git tag v${{env.GENAIZ_VERSION}}
          git push origin v${{env.GENAIZ_VERSION}}
