name: Debian Package
on:
  pull_request:
    branches:
      - '**'

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Go Setup
        uses: actions/setup-go@v6
        with:
          go-version: '1.24.2'

      - name: Go Compile
        run: |
          cd genaiz && make build

      - name: Setup Version
        run: echo "GENAIZ_VERSION=$(./genaiz/genaiz --version |cut -d' ' -f3)" >> $GITHUB_ENV

      - name: Install packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential binutils

      - name: Prepare directory structure
        run: |
          mkdir -p genaiz_${GENAIZ_VERSION}_amd64/usr/local/bin
          mkdir -p genaiz_${GENAIZ_VERSION}_amd64/DEBIAN

      - name: Copy application files
        run: |
          cp genaiz/genaiz genaiz_${GENAIZ_VERSION}_amd64/usr/local/bin/genaiz
          chmod +x genaiz_${GENAIZ_VERSION}_amd64/usr/local/bin/genaiz

      - name: Create control file
        run: |
          cat <<EOF > genaiz_${GENAIZ_VERSION}_amd64/DEBIAN/control
          Package: genaiz
          Version: ${GENAIZ_VERSION}
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: libc6
          Description: GenAIz SDK tool
          EOF

      - name: Build DEB package
        run: dpkg-deb --build --root-owner-group genaiz_${GENAIZ_VERSION}_amd64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: genaiz_${GENAIZ_VERSION}_amd64.deb
