name: genaiz_release_draft.yml

on:
  workflow_dispatch:
    inputs:
      overwrite:
        type: boolean
        description: If enabled, the version tag will be overwritten on the tree
        default: false

jobs:
  genaiz_package:
    runs-on: ops

    permissions:
      contents: write
      issues: write
      repository-projects: read

    strategy:
      matrix:
        go-version: [ '1.26.4' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --tags
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: Genaiz Dist
        id: genaiz_dist
        run: |
          cd genaiz
          go get .
          make dist
          echo "VERSION=$(./dist/genaiz --version |awk '{print $3}')" >> $GITHUB_OUTPUT
      - name: Mutually exclude duplicated tags
        if: ${{ !inputs.overwrite }}
        run: |
          existing_tag="$(git --no-pager tag -l 'v${{steps.genaiz_dist.outputs.VERSION}}' | head -1)" && \
            [ -z "$existing_tag" ] || \
              { echo 'Version ${{steps.genaiz_dist.outputs.VERSION}} is already tagged' >&2; exit 1; }
      - name: Remove existing tag on overwrite
        if: ${{ inputs.overwrite }}
        run: |
          git tag -d 'v${{steps.genaiz_dist.outputs.VERSION}}'
      - name: Create draft release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create 'v${{steps.genaiz_dist.outputs.VERSION}}-Draft' \
            --title='v${{steps.genaiz_dist.outputs.VERSION}}' \
            --notes='This is a draft' \
            --draft=true \
            --fail-on-no-commits
      - name: Create release tag
        run: |
          git config user.name genaiz_release_draft[bot]
          git config user.email genaiz_release_draft[bot]@users.noreply.github.com
          git tag v${{steps.genaiz_dist.outputs.VERSION}}
          git push origin v${{steps.genaiz_dist.outputs.VERSION}}
      - name: Upload assets
        id: upload_assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE_NAME: genaiz-${{steps.genaiz_dist.outputs.VERSION}}.tar.gz
        run: |
          gh release upload 'v${{steps.genaiz_dist.outputs.VERSION}}-Draft' \
            "./genaiz/dist/$PACKAGE_NAME#GenAIz SDK v${{steps.genaiz_dist.outputs.VERSION}}" \
            "./genaiz/dist/$PACKAGE_NAME.sha256" \
            --clobber
          BIN_URL=$(gh release view 'v${{steps.genaiz_dist.outputs.VERSION}}-Draft' \
            --json assets --jq '.assets[0] | .url')
          echo "BIN_URL=$BIN_URL" >> $GITHUB_OUTPUT
          HASH_URL=$(gh release view 'v${{steps.genaiz_dist.outputs.VERSION}}-Draft' \
            --json assets --jq '.assets[1] | .url')
          echo "HASH_URL=$HASH_URL" >> $GITHUB_OUTPUT
          DRAFT_URL=$(gh release view 'v${{steps.genaiz_dist.outputs.VERSION}}-Draft' \
            --json url --jq '.url')
          echo "DRAFT_URL=$DRAFT_URL" >> $GITHUB_OUTPUT
      - name: Create distribution ticket
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BODY: |
            As a release manager, I need to validate release [v${{steps.genaiz_dist.outputs.VERSION}}](${{steps.upload_assets.outputs.DRAFT_URL}}) before sealing it as an immutable release
            
            Release package: [genaiz-${{steps.genaiz_dist.outputs.VERSION}}.tar.gz](${{steps.upload_assets.outputs.BIN_URL}})
            Package checksum: [genaiz-${{steps.genaiz_dist.outputs.VERSION}}.tar.gz.sha256](${{steps.upload_assets.outputs.HASH_URL}})
            
            Acceptance:
            - We need a test plan with issues listed under this Epic
            - Rename the release to v${{steps.genaiz_dist.outputs.VERSION}}
            - Remove draft to seal the tag. (This will burn the tag!!! Careful)
        run: |
          gh issue create \
            --title "Validate release v${{steps.genaiz_dist.outputs.VERSION}}" \
            --type "Epic" \
            --body "$BODY"
